# Generated by Django 3.0 on 2021-08-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
