# Generated by Django 3.0 on 2021-08-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_auto_20210825_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
