# Generated by Django 3.0 on 2021-08-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0007_auto_20210825_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
