# Generated by Django 3.0 on 2021-08-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0008_auto_20210825_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
