# Generated by Django 3.0 on 2021-08-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0009_auto_20210825_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='content',
        ),
    ]
