# Generated by Django 3.0 on 2021-08-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0010_auto_20210825_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='user',
        ),
    ]
