# Generated by Django 3.0 on 2021-08-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0012_auto_20210825_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Materia')),
                ('estado', models.BooleanField(default=True, verbose_name='Materia Activada/Materia Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
