# Generated by Django 3.0 on 2021-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0013_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='materia',
            name='Descripcion',
            field=models.CharField(default=1, max_length=100, verbose_name='Descripcion de Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='Nivel',
            field=models.CharField(default=1, max_length=100, verbose_name='Nivel de complejidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, null=2, verbose_name='Nombre de la Materia'),
        ),
    ]
