# Generated by Django 3.0 on 2021-08-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0015_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
