# Generated by Django 3.0 on 2021-08-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0016_auto_20210825_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema_General',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=2, verbose_name='Nombre del Tema General')),
                ('Nivel', models.CharField(max_length=100, verbose_name='Nivel de complejidad')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion de Tema General')),
                ('estado', models.BooleanField(default=True, verbose_name='Tema General Activada/Tema General Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('materia', models.ManyToManyField(to='Curso.Materia')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
