# Generated by Django 3.0 on 2021-08-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0017_auto_20210825_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema_general',
            name='materia',
        ),
        migrations.AddField(
            model_name='tema_general',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Materia'),
        ),
    ]
