# Generated by Django 3.0 on 2021-08-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0018_auto_20210825_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema_general',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=2, verbose_name='Nombre de la Categoria')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion de Tema General')),
                ('estado', models.BooleanField(default=True, verbose_name='Tema General Activada/Tema General Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('Tema_General', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Tema_General')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
