# Generated by Django 3.0 on 2021-08-26 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0019_auto_20210825_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=2, verbose_name='Nombre de la Categoria')),
                ('link_video', models.URLField(verbose_name='Ingresa Link de Video de Vimeo')),
                ('Descripcion', models.TextField(max_length=100, verbose_name='Descripcion de Tema General')),
                ('estado', models.BooleanField(default=True, verbose_name='Articulo Activada/Articulo Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('Categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Tema_General')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
