# Generated by Django 3.0 on 2021-08-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0020_articulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='portada',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
