# Generated by Django 3.0 on 2021-08-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0021_auto_20210825_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripcion del Articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=100, null=2, verbose_name='Nombre del Articulo'),
        ),
    ]
