# Generated by Django 3.0 on 2021-08-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0022_auto_20210825_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_articulo', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=2)),
                ('entregado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
            },
        ),
    ]
