# Generated by Django 3.0 on 2021-08-31 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0023_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='entregado',
        ),
    ]
