# Generated by Django 3.0 on 2021-09-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0024_remove_pedidos_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_articulo', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='seccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='n_articulo',
            new_name='n_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='precio',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table=None,
        ),
    ]
