# Generated by Django 3.0 on 2021-09-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0025_auto_20210902_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo_1',
            name='precio',
        ),
    ]
