# Generated by Django 3.0 on 2021-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0026_remove_articulo_1_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_1',
            name='ciudad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
