# Generated by Django 3.0 on 2021-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0027_articulo_1_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ej_articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ej_articulo', models.CharField(max_length=100)),
                ('ej_categoria', models.CharField(max_length=20)),
                ('ej_ciudad', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='ej_pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ej_pedido_n', models.CharField(max_length=100)),
                ('ej_direccion_n', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
