# Generated by Django 3.0 on 2021-09-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0028_ej_articulo_ej_pedidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='Articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Articulo'),
        ),
    ]
